### ISSUE TITLE
Modify `LHDataStore` to also being able to read files without having write access

### ISSUE THREAD

**Issue by fhagemann** [legend-exp/LegendHDF5IO.jl#19]
Right now, `LHDataStore` is opened using `cw` rights, meaning that one can read and write.
However, if trying to open a file without write access, this fails.

How about making
```julia
LHDataStore(f::AbstractString) = LHDataStore(HDF5.h5open(f, "cw"))
```
something like
```julia
LHDataStore(f::AbstractString, access = "cw") = LHDataStore(HDF5.h5open(f, access))
```
?

**Comment by oschulz** [comment]
@apmypb  Let's use read-only access as the default, we should have

```
LHDataStore(f::AbstractString, access::AbstractString = "r") = LHDataStore(HDF5.h5open(f, access))
```

The default should always be to *not* change scientific data. :-)

**Comment by apmypb** [comment]
I will consider it in the next pull request

**Comment by fhagemann** [comment]
Thanks @apmypb !
