### ISSUE TITLE
`Base.size` has type instabilities

### ISSUE THREAD

**Issue by fhagemann** [legend-exp/LegendHDF5IO.jl#24]
https://github.com/legend-exp/LegendHDF5IO.jl/blob/1ced4f281e525116862595436774dfb7a879b535/src/types.jl#L192

When calling `size(lha::LH5Array)` it does not know the dimensions of `LH5Array` even though it should.
Can the `size` function be adapted such that it works like that for arrays? There, we see no type instabilities.

@apmypb

**Comment by oschulz** [comment]
Yes, `size` should definitely work.

**Comment by fhagemann** [comment]
Solved with #26
