### ISSUE TITLE
Update Project.toml

### ISSUE THREAD

**Issue by johannaluehrs** [legend-exp/LegendHDF5IO.jl#29]
The package is officially released as 0.1.4, but the Project.toml still quotes 0.1.3
https://github.com/legend-exp/LegendHDF5IO.jl/blob/e2e1419f441d9a2afe214ba548c49cbcc0be155f/Project.toml#L3

**Comment by oschulz** [comment]
Ooops, how did that happen? I'll fix it.

**Comment by oschulz** [comment]
Should be fixed now, main branch was missing a push.

**Comment by fhagemann** [comment]
Same for LegendTextIO
